[package]
name = "poisson-visualisation"
version = "0.1.0"
authors = ["WaDelma <>"]
edition = "2018"

[dependencies]
nalgebra = { version = "0.22", features = [ "alga" ] }
image = "0.23"
clap = "2"
rand = "0.7"
lab = "0.8"
fnv = "1"
poisson = { path = "../poisson" }